### ISSUE TITLE
Sporadic failures of QS/regtest-pao-2 regression tests

### ISSUE THREAD

**Issue by RMeli** [RMeli/cp2k#4]
When running the regression tests multiple times (CPU-only), I noticed sporadic failures in `QS/regtest-pao-2/H2O_pao_equi_hybrid`.

```
 PAO| energy:  -3.8705507213116932      penalty:   1.2018714590011458E-007
 PAO|LS| Need extra step
 PAO|LS| adapt:  T F T
 PAO|LS| adapt: scan_steps:    0.0000000000000000        0.0000000000000000        1.7552858190539159E-010
 PAO|LS| adapt: energies:   -3.8705507800504368        0.0000000000000000       -3.8705507213116932     

 *******************************************************************************
 *   ___                                                                       *
 *  /   \                                                                      *
 * [ABORT]                                                                     *
 *  \___/                         PAO gradient is wrong.                       *
 *    |                                                                        *
 *  O/|                                                                        *
 * /| |                                                                        *
 * / \                                                          pao_main.F:289 *
 *******************************************************************************


 ===== Routine Calling Stack ===== 

            4 pao_update
            3 ls_scf
            2 qs_energies
            1 CP2K
```

I'm struggling to reproduce this failure, but it seems to appear somewhat consistently if I run
 
```bash
./tests/do_regtest.py local psmp --mpiranks 2 --ompthreads 6 --num_gpus 0 --mpiexec "mpiexec --bind-to core:6" --restrictdir QS/regtest-pao-2
```

immediately followed by

```bash
./tests/do_regtest.py local psmp --mpiranks 1 --ompthreads 6 --num_gpus 0 --mpiexec "mpiexec --bind-to core:6" --restrictdir QS/regtest-pao-2
```

---

Sometimes, more rarely, `QS/regtest-pao-2/H2O_pao_equi` fails too (with the same error):

```
 PAO| energy:  -3.8705511958704575      penalty:   1.4947881182453469E-009
 PAO|LS| Need extra step
 PAO|LS| adapt:  T F T
 PAO|LS| adapt: scan_steps:    0.0000000000000000        0.0000000000000000        1.8532757725494762E-010
 PAO|LS| adapt: energies:   -3.8705511969708692        0.0000000000000000       -3.8705511958704575     

 *******************************************************************************
 *   ___                                                                       *
 *  /   \                                                                      *
 * [ABORT]                                                                     *
 *  \___/                         PAO gradient is wrong.                       *
 *    |                                                                        *
 *  O/|                                                                        *
 * /| |                                                                        *
 * / \                                                          pao_main.F:289 *
 *******************************************************************************


 ===== Routine Calling Stack ===== 

            4 pao_update
            3 ls_scf
            2 qs_energies
            1 CP2K

```

---

CP2K: ed1be9b29a76eae91bc5e1d9cb35fbcaa846fe6c

## CMake

```bash
cmake \
  -DCP2K_SCALAPACK_VENDOR=MKL \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DCP2K_ENABLE_REGTESTS=ON \
  -DCP2K_USE_MPI_F08=ON \
  ..
``` 

## Spack

Spack environment:

```yaml
spack:
  specs:
  - mpich device=ch3 netmod=tcp
  - intel-mkl threads=openmp
  - cosma+scalapack+shared
  - dbcsr@develop +mpi_f08
  - cp2k@master +libxc +libint +cosma +spglib +dlaf build_system=cmake 
  packages:
    all:
      variants:
      - +mpi
      - ~cuda
      - ~rocm
  repos:
  - ~/git/my-spack/repos/cp2k-dlaf/
  - ~/git/DLA-Future/spack/
  develop:
    dla-future:
      path: ~/git/DLA-Future
      spec: dla-future@master +hdf5 +scalapack ~cuda ~rocm build_type=Debug ^pika@main
  view: false
  concretizer:
    unify: true
```

```bash
spack -e ENV concretize -f
spack -e ENV install --only=dependencies
spack -e ENV build-env cp2k -- bash
```
